# Generated by Django 2.2.5 on 2019-09-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_manufacturer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('car_link', models.CharField(blank=True, max_length=100, null=True)),
                ('car_photo', models.CharField(blank=True, max_length=300, null=True)),
                ('car_year', models.CharField(blank=True, max_length=100, null=True)),
                ('car_type', models.CharField(blank=True, max_length=100, null=True)),
                ('car_engine', models.CharField(blank=True, max_length=100, null=True)),
                ('car_milage', models.CharField(blank=True, max_length=100, null=True)),
                ('car_gearbox', models.CharField(blank=True, max_length=100, null=True)),
                ('car_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapedCars.CarManufacturer')),
            ],
        ),
    ]
